import { z } from "zod";

export const heroShowcase = {
  identity: "Zahidul Islam · Full Stack & AI Engineer",
  headline: ["I build software", "that puts", "AI to work."],
  description:
    "From a grounded answer to a complete application. I connect interfaces, intelligence and infrastructure into systems people can use.",
  workspace: "EXPLORE THE ENGINEERING",
  tabLabel: "Explore engineering disciplines",
  architectureLabel: "INTELLIGENCE IN MOTION",
  detailLabel: "ENGINEERING DECISION",
  open: "Explore this project",
  hint: "Three disciplines. One connected world. Hover to hold a scene.",
  animation: {
    pause: "Pause globe and automatic cycling",
    resume: "Resume globe and automatic cycling",
    label: "Rotating engineering globe",
    automatic: "AUTO EXPLORING",
    held: "SCENE ON HOLD",
    still: "MOTION REDUCED",
    footer: "ENGINEERING IN ORBIT",
    cycleSeconds: 8,
    spinSeconds: 48,
    orbitSeconds: 14,
    pulseSeconds: 4,
    floatSeconds: 6,
    satelliteStaggerSeconds: 2,
    framesPerSecond: 30,
    pixelRatioLimit: 2,
  },
  motion: { tiltDegrees: 4, entranceSeconds: 0.55, entranceDistance: 14 },
  modes: z
    .array(
      z.object({
        id: z.string(),
        label: z.string(),
        projectId: z.string(),
        title: z.string(),
        caption: z.string(),
        nodes: z.array(z.string()).length(3),
        decision: z.string(),
        visual: z.enum(["neural", "interface", "orbital"]),
        accent: z.string(),
        core: z.string(),
        signal: z.string(),
        satelliteLabels: z.array(z.string()).length(3),
        routes: z.number().int().min(1).max(6),
      }),
    )
    .parse([
      {
        id: "ai",
        label: "AI",
        projectId: "yuktha-wellness",
        title: "Answers with a foundation.",
        caption: "Yuktha Wellness / retrieval architecture",
        nodes: ["Retrieve", "Rerank", "Ground"],
        visual: "neural",
        accent: "181, 246, 201",
        core: "GROUNDED INTELLIGENCE",
        signal: "CONTEXT → CLARITY",
        satelliteLabels: ["CONTEXT", "RELEVANCE", "EVIDENCE"],
        routes: 5,
        decision:
          "Hybrid retrieval and reranking bring relevant context to the answer. Emergency checks run before generation.",
      },
      {
        id: "applications",
        label: "Applications",
        projectId: "equipcert",
        title: "From the field to the record.",
        caption: "EquipCert AI / application architecture",
        nodes: ["Capture", "Review", "Audit"],
        visual: "interface",
        accent: "144, 222, 245",
        core: "CONNECTED EXPERIENCES",
        signal: "INTERFACE → IMPACT",
        satelliteLabels: ["INPUT", "WORKFLOW", "RECORD"],
        routes: 2,
        decision:
          "Inspection photos, signatures and corrective actions connect to tenant-aware records and audit history.",
      },
      {
        id: "cloud",
        label: "Cloud",
        projectId: "mediconnect-v3",
        title: "Connected by architecture.",
        caption: "MediConnect / cloud architecture concept",
        nodes: ["Identity", "Route", "Services"],
        visual: "orbital",
        accent: "202, 185, 255",
        core: "ORCHESTRATED SYSTEMS",
        signal: "CONNECTION → CONTINUITY",
        satelliteLabels: ["ACCESS", "TRAFFIC", "BOUNDARIES"],
        routes: 4,
        decision:
          "Regional routing and explicit service boundaries support connected care. The website is deployed; the wider platform remains in development.",
      },
    ]),
};

export type HeroMode = (typeof heroShowcase.modes)[number];
